$testsDir = 'C:\WerkFlow\Coding\Simulation\Werkflow.OpcUaSimulator.Tests'
$decompileDir = 'C:\WerkFlow\Coding\Simulation\_recovery\tests_debug\Werkflow.OpcUaSimulator.Tests'

$keepFromDecompile = @(
    'TestLogService.cs',
    'PhysicalSignalVerificationHarness.cs',
    'PhysicalPhysicsR1VerificationHarness.cs',
    'PhysicalSignalHierarchyTests.cs',
    'PhysicalSignalRegistryTests.cs',
    'PhysicalSignalTypeMapperTests.cs',
    'PhysicalSignalVerificationTests.cs',
    'PhysicalAp3R1ProfileTests.cs',
    'TechnicalLearningMachine300R1ProfileTests.cs',
    'JobGeneratorTests.cs',
    'NodeIdParserTests.cs',
    'ValidationServiceTests.cs',
    'PhysicalMachineProfileTests.cs'
)

# Remove decompiled junk from tests folder
$removePatterns = @(
    'AutoGeneratedProgram.cs',
    'R1LongRunReport.cs',
    'R1MachineReport.cs',
    'R4ProfileEvidence.cs',
    'R4PassEvaluation.cs',
    'R4CorrelationPlan.cs',
    'Ap4PassEvaluation.cs',
    'Ap4ExpectedDirection.cs'
)
foreach ($pat in $removePatterns) {
    $p = Join-Path $testsDir $pat
    if (Test-Path $p) { Remove-Item $p -Force; Write-Host "Removed $pat" }
}

foreach ($name in $keepFromDecompile) {
    $src = Join-Path $decompileDir $name
    if (Test-Path $src) {
        Copy-Item $src (Join-Path $testsDir $name) -Force
        Write-Host "Copied $name"
    }
}

# Copy UiDispatcher to App
Copy-Item 'C:\WerkFlow\Coding\Simulation\_recovery\app_debug\Werkflow.OpcUaSimulator.App\UiDispatcher.cs' 'C:\WerkFlow\Coding\Simulation\Werkflow.OpcUaSimulator.App\' -Force
